reg_t msg = p->get_csr(CSR_PENALTY_BOX_MSG);
uint8_t victim_message[8];
memcpy(victim_message, &msg, 8);
std::string script_filename = "/home/mgottscho/Git/eccgrp-ecc-ctrl/candidate_messages_spike_wrapper.sh";
std::string cmd = construct_sdecc_candidate_messages_cmd(script_filename, victim_message, 72, 64, "hsiao1970", 0);
std::string output = myexec(cmd);
std::cout << output << std::endl;
const char* output_cstr = output.c_str();
//memcpy((void*)RS1, output_cstr, output.length());
MMU.store_slow_path(RS1, output.length(), (const uint8_t*)output_cstr, 0);
